#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npx lint-staged

echo "Running PHPStan"
./vendor/bin/phpstan analyse app

echo "Running PHP CodeSniffer"
./vendor/bin/phpcs app --standard=PSR12 --exclude=PSR1.Classes.ClassDeclaration
